# Generated by Django 3.2.8 on 2022-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('order_number', models.IntegerField(verbose_name='заказ №')),
                ('price_dollars', models.IntegerField(verbose_name='стоимость,$')),
                ('delivery_time', models.DateTimeField(verbose_name='срок поставки')),
                ('price_rubs', models.IntegerField(verbose_name='стоимость в руб.')),
            ],
        ),
    ]
