# Generated by Django 3.2.8 on 2022-09-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0002_auto_20220930_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='delivery_date',
            field=models.DateField(verbose_name='срок поставки'),
        ),
    ]
