# Generated by Django 3.2.8 on 2022-09-30 12:48

from django.db import migrations, models
import table_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0003_alter_resulttable_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='price_rubs',
            field=models.FloatField(validators=[table_app.models.validate_decimals], verbose_name='стоимость в руб.'),
        ),
    ]
