# Generated by Django 3.2.8 on 2022-09-30 13:05

from django.db import migrations, models
import table_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0004_alter_resulttable_price_rubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='price_dollars',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='price_rubs',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[table_app.models.validate_decimals], verbose_name='стоимость в руб.'),
        ),
    ]
