# Generated by Django 3.2.8 on 2022-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0005_auto_20220930_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='price_rubs',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='стоимость в руб.'),
        ),
    ]
